
services:
  mavros:
    build:
      context: .
    image: numech/mavros-core:latest
    container_name: mavros
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      ROS_DOMAIN_ID: 0
      GCS_IP: 192.168.1.13