version: '3.8'
services:
  mavros:
    image: mavros-core:latest
    container_name: mavros
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp